### ISSUE TITLE
UI Layout Issue with multiple Recording Targets (NASes)

### ISSUE THREAD

**Issue by gibxxi** [Silicondust/dvr_install#10]
The User interface for the QNAP HDHomeRun QPKG is not displaying all recording targets correctly (See screenshot):

https://1drv.ms/u/s!Am5WO9nIAax8gbQ3-GZYE73BeTbOYg?e=iJRc7H

The second recording target is missing a title, and the vertical position of the item is incorrect (Viewed in Firefox 68.0.2).

I have both my NAS devices set-up as recording targets for redundancy purposes, in case that matters. So the QPKG is installed (and active) on both.

Gib.

**Comment by demonrik** [comment]
thanks - I think there is another bug going on here.
Looks like your first engine has the name of the connect.. and then is blank for second engine.
Will investigate

**Comment by gibxxi** [comment]
The issue seems to be solved with 0.10.4 version @demonrik. The bug was reported running 0.10.2, and since updating, everything is being displayed as expected (so far).

EDIT: I've also updated the Record Engine to v.20190815beta1, so that may have some bearing.

Dan / Gib.

**Comment by demonrik** [comment]
Even better..
There was a short lived bug with the title processing - can't remember when I fixed it.. but glad it's no longer exhibiting it.. Closing the issue.
